### ISSUE TITLE
好棒的项目~

### ISSUE THREAD

**Issue by GT-ZhangAcer** [LSTM-Kirigaya/MaplessNavigation#1]
你好Kirigaya大佬，之前有朋友向我推荐了你这个基于飞桨的强化项目，和周围朋友聊了一下都感觉很不错，可否加一下联系方式进行交流呢~(滑稽脸)

**Comment by LSTM-Kirigaya** [comment]
抱歉，我还是太菜了，与你交流会让你失望的。而且我现在才大二，许多东西还在探索中，如果需要交流的话，我们可以在GitHub或者知乎上一起交流（知乎可以私信的），我在知乎的id是锦恢，或者搜索pybullet笔记也能看到（有关pybullet和parl我都写过笔记）。
我还是不怎么习惯加陌生人联系方式啦，不好意思了o(￣┰￣*)ゞ。（其实主要是我太菜了）

**Comment by GT-ZhangAcer** [comment]
大佬谦虚啦~我挺菜的，刚大四哈哈哈

**Comment by GT-ZhangAcer** [comment]
拜读了一下大佬的笔记，受益匪浅，感谢感谢
